# Generated by Django 5.2.7 on 2025-10-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_auth_is_admin_alter_auth_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
