# Generated by Django 5.2.7 on 2025-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_auth_is_admin_alter_auth_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
