# Generated by Django 5.2.7 on 2025-11-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, unique=True)),
                ('slug', models.TextField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=225)),
                ('image_categoria', models.ImageField(blank=True, upload_to='fotos/categories')),
            ],
        ),
    ]
